micronaut:
  application:
    name: emailMicroservice
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  email:
    from:
      email: annakrasowska2+sendgrid@gmail.com
#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES
#jpa.default.properties.hibernate.hbm2ddl.auto: update
#kafka.bootstrap.servers: localhost:9092
netty:
  default:
    allocator:
      max-order: 3
sendgrid:
  api-key: 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
