micronaut:
  application:
    name: emailMicroservice
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

    enabled: ${SECURITY_ENABLED:false}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  email:
    from:
      email: ${EMAIL_FROM:annakrasowska2+mailjet@gmail.com}
  server:
    cors:
      enabled: true
kafka:
  bootstrap:
    servers: 51.38.132.138:9092
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
datasources:
  default:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/email-microservice}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME:email-microservice}
    password: ${DATABASE_PASSWORD:anna}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
#kafka.bootstrap.servers: localhost:9092
netty:
  default:
    allocator:
      max-order: 3
mailjet:
  api-key: ${MAILJET_API_KEY}
  api-secret: ${MAILJET_API_SECRET}